### ISSUE TITLE
Add new user-role 'Host' & update authorizations

### ISSUE THREAD

**Issue by UsperX** [careerfairsystems/nexpo-backend-nova#117]
Currently, solely the admin can scan tickets for events, resulting in all event coordinators and hosts needing admin privileges during the fair. This works but presents a security risk as these users get full privileges in the system. 

Our suggestion is to create a new role 'Host' that solely gets privileges aimed at fair activities (such as scanning tickets) and thereby keep the number of admin users limited. 

Todo: 
- [ ] Add 'Host' in Role in User
- [ ] Update authorizations in all relevant controllers
- [ ] Add host-users in seeding data
- [ ] Add/Update tests to verify the new behaviour

**Comment by AlexanderHansson4225** [comment]
Outdated
