### ISSUE TITLE
update student with empty string does not works

### ISSUE THREAD

**Issue by UsperX** [careerfairsystems/nexpo-backend-nova#74]
When sendeing a PUT-request to:
> api/students/me

with the example payload:
```ts
{
  guild: 1
  year: 4
  masterTitle: "Project management in software systems"  
  linkedIn: ""
}
```
I would like the linkedIn to update in the database to an empty string.
The response I get now is:
```ts
{
  id: -1
  guild: 1
  resumeEnUrl: null
  resumeSvUrl: null
  linkedIn: "hjehjehjehje"
  masterTitle: "Project management in software systems"
  year: 4
  userId: -2
}
```
Here the linkedIn is the same as before the put request

**Comment by UsperX** [comment]
At the moment, when updating a students information, the controller checks for each attribute in the UpdateStudentDto if it is not null or empty as a way to determine if it should change the attribute or not. This is mainly to prevent unintended overwrites and may introduce risks if changed. 
Taking this into account I can see two potential solutions: 
1. Change so that instead of checking null or empty, just check null. In this scenario is it only allowed to send attributes that are intended to be updated, otherwise they will be overwritten. 
2. Decide that an "empty" string containing only a space character (i.e " ") and add a trim() statement to the controller and thereby achieve the same behaviour without needing to change the check of null or empty.

**Comment by jonatan1kruse** [comment]
The way we send the Dtos from frontend now we always send the previous value in the dto if it was not edited by the user, but I will check the code and see that this is always correct. 

If that is the case I see no trouble with sending empty data to "erase" previous data. Right now there is no way to erase it. 

Talk more on Monday.

**Comment by jonatan1kruse** [comment]
I think behaviour NBR 1 is preferred, at least from frontends perspective.
This goes for update student and user

@UsperX

**Comment by UsperX** [comment]
Hm... We can discuss this during today's meeting, but it seems like an unnecessary overhead to always send all attributes in an update as the DTOs used currently supports only sending the changed attributes and thereby reduces the risk of unintended changes.
